name: Build MacOS App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Root Dependencies
        run: npm install

      - name: Build Web App (Vite)
        run: npm run build

      - name: Install MacOS App Dependencies
        working-directory: "./Desktop App/MacOS"
        run: npm install

      - name: Build Electron MacOS App
        working-directory: "./Desktop App/MacOS"
        run: npm run build

      - name: Upload MacOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StellarShip-MacOS
          path: "Desktop App/MacOS/release/*.dmg"
          if-no-files-found: error
